Facet links and updated data links
nulib/meadow pull request #1243
Opened 2020-09-28 12:54 UTC by katdivyareddy10

<img width="658" alt="Screen Shot 2020-09-28 at 7 54 21 AM" src="https://user-images.githubusercontent.com/14085957/94434724-d317b800-015f-11eb-8aaa-d17bca382379.png">

2020-09-28 14:42 UTC, adamjarling requested changes
![image](https://user-images.githubusercontent.com/3020266/94447041-fac24c80-016e-11eb-9793-965007fa135a.png)

2020-09-28 14:43 UTC, adamjarling commented
Code looks solid.  Just a few UX upgrades to polish it up:)

2020-09-29 18:51 UTC, katdivyareddy10 commented
This looks really good @adamjarling ! Thank you for taking time to work on this branch.

2020-09-29 18:52 UTC, adamjarling approved these changes

2020-09-29 18:52 UTC, merged