Ingest sheet simplified with preview and facetlinks
nulib/meadow pull request #1286
Opened 2020-10-06 17:17 UTC by katdivyareddy10

<img width="839" alt="Screen Shot 2020-10-06 at 12 11 53 PM" src="https://user-images.githubusercontent.com/14085957/95237501-ec5add00-07cd-11eb-9ed6-84582f5f52a8.png">

2020-10-07 13:07 UTC, adamjarling requested changes
A few design requests...

![image](https://user-images.githubusercontent.com/3020266/95334711-12d35380-0874-11eb-8db6-3237e1ae81b8.png)

2020-10-07 13:10 UTC, adamjarling commented on assets/js/components/BatchEdit/PreviewItems.js
> +      </ul>
How about we extract this component to the `/UI` directory now that we're using it in 2 different places.

2020-10-07 14:21 UTC, divyareddynu commented
@adamjarling I pushed changes.
<img width="1212" alt="Screen Shot 2020-10-07 at 9 21 18 AM" src="https://user-images.githubusercontent.com/72217877/95343735-7b273280-087e-11eb-84f7-4c83c1f3bdee.png">

2020-10-08 14:11 UTC, adamjarling requested changes

2020-10-08 14:11 UTC, adamjarling commented on assets/js/components/UI/Image.jsx
> +import React from "react";
Can we change the title of this file to `assets/js/components/UI/WorkImage.jsx`?

2020-10-08 14:11 UTC, adamjarling commented on assets/js/components/UI/Image.test.js
> +import React from "react";
Same here, file title to `assets/js/components/UI/WorkImage.test.js`

2020-10-08 14:11 UTC, adamjarling commented on assets/js/components/UI/PreviewItems.js
> +export default function PreviewItems({ items = [] }) {
Following our naming convention pattern, this should be `export default function UIPreviewItems({ items = [] }) {`

2020-10-08 14:11 UTC, adamjarling commented on assets/js/components/UI/PreviewItems.js
> +PreviewItems.propTypes = {
Same here, `UIPreviewitems.propTypes = ...`

2020-10-08 14:11 UTC, adamjarling commented on assets/js/components/UI/PreviewItems.test.js
> +import PreviewItems from "./PreviewItems";
And then when we import it, `import UIPreviewItems from "./UIPreviewItems";`  ...and we'll continue the new variable title throughout the code.

2020-10-08 14:11 UTC, adamjarling commented on assets/js/components/Work/CardItem.jsx
> +} from "../../services/helpers";
Again, not a huge deal, but we can start using this pattern for aliasing relative paths when importing nested components:

```
import {
  setVisibilityClass,
  formatDate,
  getImageUrl,
} from "@js/services/helpers";
```

2020-10-08 14:11 UTC, adamjarling commented on assets/js/services/helpers.js
> +
Can we add a test for this function?  What happens if `representativeImage` is undefined, or an empty string?   It'd be nice if this returned an empty string as a default.

2020-10-09 13:28 UTC, divyareddynu commented
@adamjarling it looks like you may have reviewed an older version or my changes did not pull through. I will add using `@js` notation and push a PR in a bit. Can you delete your branch and re-import it?

2020-10-09 13:54 UTC, adamjarling commented
Ooops, sorry about that.

2020-10-09 16:08 UTC, merged