EDTF dates front end for single work edit
nulib/meadow pull request #1459
Opened 2020-11-05 17:24 UTC by divyareddynu

Please test for single work edit mode
<img width="999" alt="Screen Shot 2020-11-05 at 11 23 56 AM" src="https://user-images.githubusercontent.com/72217877/98274731-66ab8800-1f59-11eb-8ba1-7c3d7807c808.png">

2020-11-05 18:05 UTC, kdid commented
Works exactly as expected!

2020-11-05 18:06 UTC, kdid approved these changes

2020-11-05 18:09 UTC, divyareddynu commented
> Works exactly as expected!

perfect! Thank you! Will add this to batchEdit and push out shortly.

2020-11-05 22:41 UTC, divyareddynu commented
@davidschober For dateCreated & relatedURL, do we want to provide an option to remove/replace values, like we do for Physical metadata?

2020-11-06 11:56 UTC, davidschober commented
Yes.

Sent from my iPhone

On Nov 5, 2020, at 4:42 PM, divyareddynu <notifications@github.com> wrote:

﻿

@davidschober<https://urldefense.com/v3/__https://github.com/davidschober__;!!Dq0X2DkFhyF93HkjWTBQKhk!FrP6EYNbKunCCLTkHrdbldeQFQKlDp84DnMAJXuZeYL3hYHh3Mku9csQNgoBD8UOT7JEye3H4A$> For dateCreated & relatedURL, do we want to provide an option to remove/replace values, like we do for Physical metadata?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://urldefense.com/v3/__https://github.com/nulib/meadow/pull/1459*issuecomment-722687396__;Iw!!Dq0X2DkFhyF93HkjWTBQKhk!FrP6EYNbKunCCLTkHrdbldeQFQKlDp84DnMAJXuZeYL3hYHh3Mku9csQNgoBD8UOT7Iwau3yjA$>, or unsubscribe<https://urldefense.com/v3/__https://github.com/notifications/unsubscribe-auth/ABEUVHQ2DKHNG75KWZAUWMLSOMS3XANCNFSM4TLUZDEA__;!!Dq0X2DkFhyF93HkjWTBQKhk!FrP6EYNbKunCCLTkHrdbldeQFQKlDp84DnMAJXuZeYL3hYHh3Mku9csQNgoBD8UOT7JWsDZjMg$>.

2020-11-09 14:35 UTC, kdid approved these changes

2020-11-10 21:34 UTC, adamjarling commented
@divyareddynu I can't seem to get this to work.  If I enter "300 BC" it tells me invalid date, but I'm not sure what I need to do to correct it? 

Also, will there only be one form field... the text input?   If so, do we want it to look like a Controlled Term display, or more like the Uncontrolled Term Field Array display?

![image](https://user-images.githubusercontent.com/3020266/98736271-381f1a00-236a-11eb-8841-e329e62442fa.png)

2020-11-10 21:35 UTC, adamjarling commented
Also, looks like the layout changed pretty substantially from `deploy/staging`.  I'd like to keep the existing layout, and just plug this EDTF date into it.

![image](https://user-images.githubusercontent.com/3020266/98736424-6866b880-236a-11eb-9fa8-60f71cf1875e.png)

2020-11-10 21:36 UTC, adamjarling requested changes
Let's make sure we're not reverting UI updates to the Work About tab form layout.

2020-11-10 21:38 UTC, divyareddynu commented
> Let's make sure we're not reverting UI updates to the Work About tab form layout.

Ok, I still wonder what is missing. I'll grab latest changes one more time and rebase.

2020-11-10 21:40 UTC, adamjarling commented on assets/js/components/UI/Form/BatchFieldArray.jsx
> +    append({ metadataItem: defaultValue });
This is a regression which we don't want implemented.  From this PR:  https://github.com/nulib/meadow/pull/1462/files

2020-11-10 21:47 UTC, adamjarling commented
@divyareddynu Looks like something went wrong rebasing your branch.   There's a lot of older code in this which we don't want to enter back in.  I wonder if there's a way to create a new branch, and extract ONLY the pieces of code you changed into the new EDTF branch?    

Again, make sure you're always doing a `git rebase deploy/staging` into whatever feature branch you're working on to make sure you're putting your work _on top_ of any previous commits.

2020-11-11 14:32 UTC, divyareddynu commented
This has been added at https://github.com/nulib/meadow/pull/1485 closing this.

2020-11-11 14:32 UTC, closed without merging