1107 batch management
nulib/meadow pull request #1521
Opened 2020-11-23 15:04 UTC by kdid

2020-11-23 16:11 UTC, mbklein commented
I like the overall design, especially the unique boolean field on the batches table. Fits in nicely with the “let the database do the work when possible” approach. I think there's a good opportunity here to use the `DatabaseNotification` module to build a pass-through GraphQL subscription to notify the front-end of status changes.

2020-11-23 17:34 UTC, bmquinn reviewed
I think this looks great! I like the `unique_index` approach you took. Added a couple small comments as well.

2020-11-23 17:34 UTC, bmquinn commented on lib/meadow/batch_driver.ex
> +        Logger.info("No batches queued")
It's a fine line with logging always, but my take here is this adds extra noise to the log. Would maybe just do `nil -> :noop` instead

2020-11-23 17:34 UTC, bmquinn commented on lib/meadow/data/schemas/batch.ex
> +    |> unique_constraint(:active)
You could add `|> validate_inclusion(:status, ["complete", "error", "in_progress"])` for an extra data integrity check here as well

2020-11-30 22:09 UTC, mbklein reviewed
What is the purpose of the new `batch_ids` field in the work schema? I'm not sure batches (which represent an ephemeral process) need to be as part of the permanent representation of a work. I also can't find where they're used – just created and updated. If there needs to be a link between the batches table and the works affected by each batch, I'd rather have a separate table that links `batch_id` to `work_id` (or at least which keys on one and stores the other as an array).

2020-11-30 22:11 UTC, bmquinn requested changes

2020-11-30 22:11 UTC, bmquinn commented on test/meadow/batches_test.exs
> +      query =
Looks like you can yank this `query` variable being set here and just use `attrs` (I saw an unused variable warning in the console)

2020-11-30 22:52 UTC, kdid commented on test/meadow/batches_test.exs
> +      query =
I don't think there needs to be an actual link between the tables. We just need to index the id's so we can link into a faceted search. 

I hear what you are saying but I think we already have had discussions about how our postgres record of the work is not the preservation object and it has some other stuff on it - like the ingest_sheet_id. I remember talking about that in regards to ingest_sheets and projects....

I was just trying to do the simplest thing possible. We can talk further tomorrow if you want.

2020-12-03 16:30 UTC, mbklein commented
I got this error while trying to submit a batch.

![image](https://user-images.githubusercontent.com/196872/101058121-6b605d80-3552-11eb-83b1-32303e690028.png)

I think `add`, `delete`, `replace`, and `query` might need to be of type `text`, not `string(255)`.

2020-12-03 16:51 UTC, bmquinn approved these changes
Looks awesome, my only suggestion would be that we should keep an eye on reducing the 6 minute interval. My guess is we can lower it since the GenServer behaviour does a nice job of handling long-running interval tasks, which would mean less wait time for metadata folks 😄

2020-12-03 17:43 UTC, mbklein approved these changes
Agree with @bmquinn. The interval is the time between the _end_ of one run and the _beginning_ of the next, so a new task will never be fired while an existing one is running (assuming there's only one process running them). But I don't think that's a reason to hold up merging.

2020-12-03 18:04 UTC, merged