Add total works to collections queries and clean up placeholder data
nulib/meadow pull request #1951
Opened 2021-03-05 21:59 UTC by kdid

- Adds totalWorks to GraphQL collection queries
- Add total works and truncated description to collection list page, clean up placeholder data
- On individual collection pages:
  - display total works
  - don't display view all works button or update image link if the collection has no works
  - respect newlines in description text

<hr>
<img width="1422" alt="Screen Shot 2021-03-05 at 2 49 32 PM" src="https://user-images.githubusercontent.com/6372022/110177941-fc99d700-7dc2-11eb-870b-9062cfbf2861.png">

<img width="1456" alt="Screen Shot 2021-03-05 at 2 58 26 PM" src="https://user-images.githubusercontent.com/6372022/110178145-45ea2680-7dc3-11eb-8456-a2c6990cad6d.png">

<img width="1383" alt="Screen Shot 2021-03-05 at 1 41 56 PM" src="https://user-images.githubusercontent.com/6372022/110178016-12a79780-7dc3-11eb-9f60-e6dc408892d0.png">

2021-03-05 22:12 UTC, mbklein requested changes

2021-03-05 22:12 UTC, mbklein commented on lib/meadow/data/collections.ex
> +  end
Ecto has a [convenience method](https://hexdocs.pm/ecto/Ecto.Repo.html#c:aggregate/3) for this:
```
from(w in Work, where: w.collection_id == ^collection_id)
|> Repo.aggregate(:count)
```
It always returns either a number or `nil`, so no error checking needed.

2021-03-05 23:45 UTC, mbklein approved these changes

2021-03-08 15:12 UTC, adamjarling commented on assets/js/services/helpers.js
> +}
This totally works, but wouldn't hurt to provide a default param to `text` (`truncateText(text = "", number)`).

And if you wanted to learn something cool about forward-thinking React code, this helper (and all helpers for that matter) could be a hook instead.   In 2 years, say someone other than us was reading the code the convention may be more familiar to them.

```
export default function useTruncateText() {
  function truncate(text, number) {
  ... 
  }
  return { truncate };
}

// usage
import useTruncateText from '@js/hooks/use-truncate-text'
...
const { truncate } = useTruncateText();
truncate("foobaz", 50);
```

2021-03-08 19:42 UTC, merged