Reshape FileSet metadata
nulib/meadow pull request #2238
Opened 2021-05-25 19:26 UTC by mbklein

* Rename FileSet `metadata` field to `core_metadata` / `coreMetadata`
* Add `extracted_metadata` / `extractedMetadata`
* Move existing extracted metadata from `metadata` to `extracted_metadata`
* Update GraphQL queries and mutations
* Update front-end components
* Update all back- and front-end tests

This PR includes both forward and backward data migrations, as well as code to ensure that seed data and migration manifests created before the change will still import and migrate properly.

2021-05-25 20:56 UTC, bmquinn commented
@mbklein I'm seeing an error uploading a FileSet through the UI, though the logs aren't adding any helpful information to copy/paste:

![add_fileset_error](https://user-images.githubusercontent.com/1395707/119567191-a1e49b80-bd71-11eb-9829-f492dd1821db.png)

Tested on staging to verify, no error there.

2021-05-25 20:57 UTC, bmquinn commented
After uploading the screenshot, I realized the error shows `ingestfileSet` when it should be `ingestFileSet`

2021-05-25 20:59 UTC, bmquinn requested changes
Found it!

2021-05-25 20:59 UTC, bmquinn commented on assets/js/components/Work/Tabs/Preservation/FileSetModal.jsx
> +          `FileSet record id: ${ingestFileSet.id} created successfully and ${ingestfileSet.coreMetadata.original_filename} was submitted to the ingest pipeline.`
```suggestion
          `FileSet record id: ${ingestFileSet.id} created successfully and ${ingestFileSet.coreMetadata.original_filename} was submitted to the ingest pipeline.`
```

2021-05-25 21:12 UTC, mbklein commented on assets/js/components/Work/Tabs/Preservation/FileSetModal.jsx
> +          `FileSet record id: ${ingestFileSet.id} created successfully and ${ingestfileSet.coreMetadata.original_filename} was submitted to the ingest pipeline.`
Fixed and force-pushed.

2021-05-25 21:14 UTC, bmquinn approved these changes

2021-05-26 13:03 UTC, kdid approved these changes

2021-05-26 15:45 UTC, adamjarling approved these changes
Looks good and straight forward enough to me on the front-end.  I'll definitely need to rebase on this for what I'm working on.

2021-05-26 16:00 UTC, merged