Add wrapping logic to batch edit notes.
nulib/meadow pull request #2965
Opened 2022-03-14 20:57 UTC by mathewjordan

# Summary 
Brief high level description of this feature or fix

# Specific Changes in this PR
- list changes
- list changes
# Version bump required by the PR

See [Semantic Versioning 2.0.0](https://semver.org/) for help discerning which is required.

- [x] Patch
- [ ] Minor
- [ ] Major

# Steps to Test
Please let end users know what they need to do to test on staging or production

Also please let developers know if there are any special instructions to test this in the development environment. 

# :rocket: Deployment Notes

**Note** - __if you check any of these boxes go to the [(always open) `main` <- `staging` PR](https://github.com/nulib/meadow/pulls) and add detailed notes and instructions to help out others who may end up deploying your changes to production__

- Backward compatible API changes
  - [ ] Database Schema changes
  - [ ] GraphQL API
  - [ ] Elasticsearch API
  - [ ] Ingest Sheet
  - [ ] CSV metadata export/update API
  - [ ] Shared Links export API
- Backwards-incompatible API changes
  - [ ] Database Schema changes
  - [ ] GraphQL API
  - [ ] Elasticsearch API
  - [ ] Ingest Sheet
  - [ ] CSV metadata export/update API
  - [ ] Shared Links export API
- [ ] Requires data migration
- [ ] Requires database triggers disabled during deployment/migration
- [ ] Requires reindex
- [ ] Terraform changes
  - [ ] Adds/requires new or changed Terraform variables
- [ ] Pipeline configuration changes (requires `mix meadow.pipeline.setup` run)
- [ ] Requires new variable added to `miscellany`
- [ ] Specific deployment synchronization instructions with other apps/API's
- [ ] Other specific instructions/tasks

# Tested/Verified
- [ ] End users/stakeholders

2022-03-15 15:13 UTC, mbklein commented
@mathewjordan Try rebasing on `deploy/staging` – there’s a cache key in the build spec that’s pointing to a bad cache.

2022-03-16 19:50 UTC, adamjarling requested changes
See screenshots on some stuff I'm seeing.  Note the "Reading Room" value showing up in the Batch Confirmation window happens on `deploy/staging` branch for me too.

But the other issue happens for me when:
1. I add either a Notes or Related URL value(2), and click to go to Confirmation modal.
2. In Confirmation modal, click "Cancel"
3. Remove the added items for Notes and/or Related URL.  Proceed to Confirmation modal again.
4. Notice if you chose to "Replace" these items, a record of them still exists in the Confirmation modal, even though they were deleted.

<img width="1495" alt="image" src="https://user-images.githubusercontent.com/3020266/158676569-6d294a60-3098-4c29-810c-fa12155b66fd.png">

2022-03-16 19:57 UTC, mathewjordan commented
> See screenshots on some stuff I'm seeing. Note the "Reading Room" value showing up in the Batch Confirmation window happens on `deploy/staging` branch for me too.
> 
> But the other issue happens for me when:
> 
>     1. I add either a Notes or Related URL value(2), and click to go to Confirmation modal.
> 
>     2. In Confirmation modal, click "Cancel"
> 
>     3. Remove the added items for Notes and/or Related URL.  Proceed to Confirmation modal again.
> 
>     4. Notice if you chose to "Replace" these items, a record of them still exists in the Confirmation modal, even though they were deleted.
> 
> 
> <img alt="image" width="1495" src="https://user-images.githubusercontent.com/3020266/158676569-6d294a60-3098-4c29-810c-fa12155b66fd.png">

Thanks. Taking a look.

2022-03-16 20:00 UTC, adamjarling commented on assets/js/components/BatchEdit/Tabs.jsx
> +import { forEach } from "lodash";
Do we need to use `lodash`s version of `forEach` here?

2022-03-16 20:01 UTC, adamjarling reviewed
@mathewjordan Code looks solid and minimal.  Nice work.

2022-03-16 20:42 UTC, mathewjordan commented
The Reading Room thing looks unrelated and introduced elsewhere. I'll write up an issue for this.

![image](https://user-images.githubusercontent.com/7376450/158687144-f78347a0-b623-4a95-ab0e-14d5f8d20de4.png)

2022-03-18 15:01 UTC, adamjarling approved these changes
Looking good!

2022-04-04 14:19 UTC, merged