Adjust regex to ensure a starts with on URL pattern protocol.
nulib/meadow pull request #2975
Opened 2022-03-17 18:21 UTC by mathewjordan

# Summary 
URL Pattern matching was checking for any part of the string input into the URL field to start with `http://` or `https://`. In that case an input value of `foo https://bar.baz` would validate TRUE. This now validates false and will require a url to match a pattern of: `https://foo.bar`

# Specific Changes in this PR
- Adjusts URL validation to make sure URL strings start with either `http://` or `https://`

# Version bump required by the PR

See [Semantic Versioning 2.0.0](https://semver.org/) for help discerning which is required.

- [x] Patch
- [ ] Minor
- [ ] Major

# Steps to Test

1. Edit any work
2. Add a Related URL of "foo https://bar.baz"
3. This should fail validation ❌ 
2. Add a Related URL of " https://foo.bar"
3. This should pass validation ✅ 

# :rocket: Deployment Notes

**Note** - __if you check any of these boxes go to the [(always open) `main` <- `staging` PR](https://github.com/nulib/meadow/pulls) and add detailed notes and instructions to help out others who may end up deploying your changes to production__

- Backward compatible API changes
  - [ ] Database Schema changes
  - [ ] GraphQL API
  - [ ] Elasticsearch API
  - [ ] Ingest Sheet
  - [ ] CSV metadata export/update API
  - [ ] Shared Links export API
- Backwards-incompatible API changes
  - [ ] Database Schema changes
  - [ ] GraphQL API
  - [ ] Elasticsearch API
  - [ ] Ingest Sheet
  - [ ] CSV metadata export/update API
  - [ ] Shared Links export API
- [ ] Requires data migration
- [ ] Requires database triggers disabled during deployment/migration
- [ ] Requires reindex
- [ ] Terraform changes
  - [ ] Adds/requires new or changed Terraform variables
- [ ] Pipeline configuration changes (requires `mix meadow.pipeline.setup` run)
- [ ] Requires new variable added to `miscellany`
- [ ] Specific deployment synchronization instructions with other apps/API's
- [ ] Other specific instructions/tasks

# Tested/Verified
- [ ] End users/stakeholders

2022-03-17 19:22 UTC, mathewjordan commented
@adamjarling For your eyes when you return.

2022-03-18 15:09 UTC, adamjarling requested changes
@mathewjordan This looks good for Batch Edit, however can we apply the same error message display to a single Work Edit?   

To test: in Work Edit, enter "asdf http://google.com" for "Related Url".  The form doesn't submit (which is probably good), but guessing the validation error just isn't getting communicated in the UI?

2022-03-18 15:11 UTC, adamjarling commented on assets/js/services/helpers.js
> +    ? true
You probably don't even need lines 29-30 here.  Guessing it'll coerce to truthy?

2022-04-18 12:18 UTC, mathewjordan reviewed
@adamjarling I dug into this a bit more to try and remember what we are doing here. It looks like all the validation here happens during the attempted submission process. Do we want to switch this up so that some minimal feedback is given during each onChange?

2022-04-18 13:03 UTC, adamjarling commented
@mathewjordan Either way as long as it's good UX, I'm fine pre-handling the submission or the alternative was React Hook Form catches the validation error and displays the error message prior to sending off the network request?

2022-05-23 14:34 UTC, closed without merging